package com.Flight_Reservation_app.utilities;
import java.io.FileOutputStream;
import java.util.Date;

import org.springframework.stereotype.Component;

import com.Flight_Reservation_app.entity.Reservation;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;

@Component
public class PdfGenerator {//This is the copied file from sir's.
	 
//    private static Font catFont = new Font(Font.FontFamily.TIMES_ROMAN, 18,
//            Font.BOLD);
//    private static Font smallBold = new Font(Font.FontFamily.TIMES_ROMAN, 12,
//            Font.BOLD);
    
    public void generateItenerary(Reservation reservation, String filePath) {
    	Document document = new Document();
    	try {
			PdfWriter.getInstance(document, new FileOutputStream(filePath));
			
			document.open();
			document.add(generateTable(reservation));
			document.close();
		} catch (Exception e) {
			e.printStackTrace();
		}
    }
    
    private PdfPTable generateTable(Reservation reservation) {
    	
    	PdfPTable table = new PdfPTable(2);//First we created a table with 2 columns.
    	PdfPCell cell;//In that table we need to create cells and for that we declare a cell local reference variable.
    	
    	cell = new PdfPCell(new Phrase("Flight Itinarary"));
    	cell.setColspan(2);//To merge 2 columns we use this statement.
    	table.addCell(cell);//Then we are adding the cell into table.
    	
    	cell = new PdfPCell(new Phrase("Flight Details"));
    	cell.setColspan(2);
    	table.addCell(cell);
    	
    	table.addCell("Departure City");
    	table.addCell(reservation.getFlight().getDepartureCity());
    	
    	table.addCell("Arrival City");
    	table.addCell(reservation.getFlight().getArrivalCity());
    	
    	table.addCell("Operating AirLine");
    	table.addCell(reservation.getFlight().getOperatingAirlines());
    	
    	table.addCell("Departure Date");
    	table.addCell(reservation.getFlight().getDateOfDeparture().toString());//addCell doesn't take Date datatype, therefore we convert it to toString()
    	
    	table.addCell("Departure Time");
    	table.addCell(reservation.getFlight().getEstimatedDepartureTime().toString());
    	
    	cell = new PdfPCell(new Phrase("Passenger Details"));
    	cell.setColspan(2);
    	table.addCell(cell);
    	
    	table.addCell("First Name");
    	table.addCell(reservation.getPassenger().getFirstName());
    	
    	table.addCell("Middle Name");
    	table.addCell(reservation.getPassenger().getMiddleName());
    	
    	table.addCell("Last Name");
    	table.addCell(reservation.getPassenger().getLastName());
    	
    	table.addCell("Email Id");
    	table.addCell(reservation.getPassenger().getEmail());
    	
    	
    	table.addCell("Mobile No");
    	table.addCell(reservation.getPassenger().getPhone());
    	
    	return table;
    }
    
//    public  void generatePDF(String filePath, String name, String emailId, String phone, String operatingAirlines, Date departureDate, String departureCity, String arrivalCity) {
//        try {
//            Document document = new Document();
//            PdfWriter.getInstance(document, new FileOutputStream(filePath));
//            document.open();
//            addMetaData(document);
//            addTitleAndTable(document,name,emailId,phone,operatingAirlines, departureDate.toString(),departureCity,arrivalCity);
//           
//            document.close();
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
//    }
//
//    // iText allows to add metadata to the PDF which can be viewed in your Adobe
//    // Reader
//    // under File -> Properties
//    private static void addMetaData(Document document) {
//        document.addTitle("My first PDF");
//        document.addSubject("Using iText");
//        document.addKeywords("Java, PDF, iText");
//        document.addAuthor("Lars Vogel");
//        document.addCreator("Lars Vogel");
//    }
//
//    private static void addTitleAndTable(Document document, String name, String emailId, String phone, String operatingAirlines, String departureDate, String departureCity, String arrivalCity)
//            throws DocumentException {
//        Paragraph preface = new Paragraph();
//        
//        
//        preface.add(new Paragraph("Flight Booking Details", catFont));
//
//       
//        preface.add(new Paragraph(
//                "Report generated by: " + "Flight Reservation Company " + new Date(), //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$
//                smallBold));
//       
//        document.add(preface);  
//        document.add( Chunk.NEWLINE );
//        document.add( Chunk.NEWLINE );
//        
//        
//        PdfPTable table = new PdfPTable(2);
//        table.setWidthPercentage(100);
//        // t.setBorderColor(BaseColor.GRAY);
//        // t.setPadding(4);
//        // t.setSpacing(4);
//        // t.setBorderWidth(1);
//
//        PdfPCell c1 = new PdfPCell(new Phrase("Passenger Detail"));
//        c1.setHorizontalAlignment(Element.ALIGN_CENTER);
//        c1.setColspan(2);
//        table.addCell(c1);
//
//        table.addCell("Passenger name");
//        table.addCell(name);
//        table.addCell("Email Id");
//        table.addCell(emailId);
//        table.addCell("Phone Number");
//        table.addCell(phone);
//        
//        document.add(table);
//        
//        
//        PdfPTable table1 = new PdfPTable(2);
//        table1.setWidthPercentage(100);
//        // t.setBorderColor(BaseColor.GRAY);
//        // t.setPadding(4);
//        // t.setSpacing(4);
//        // t.setBorderWidth(1);
//
//        PdfPCell c2 = new PdfPCell(new Phrase("Flight Detail"));
//        c2.setHorizontalAlignment(Element.ALIGN_CENTER);
//        c2.setColspan(2);
//        table1.addCell(c2);
//
//        table1.addCell("Operating Airlines");
//        table1.addCell(operatingAirlines);
//        table1.addCell("Departure Date");
//        table1.addCell(departureDate);
//        table1.addCell("Departure City");
//        table1.addCell(departureCity);
//        
//        table1.addCell("Arrival City");
//        table1.addCell(arrivalCity);
//        
//        document.add(table1);
//       
//        document.close();
//    }

  
}
