package com.Flight_Reservation_app.utilities;

import java.io.FileOutputStream;
import java.util.Date;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;

public class PDFGeneratorDeprecated {//We are not referring this file.
	 
    private static Font catFont = new Font(Font.FontFamily.TIMES_ROMAN, 18,
            Font.BOLD);
    private static Font smallBold = new Font(Font.FontFamily.TIMES_ROMAN, 12,
            Font.BOLD);
    
    public  void generatePDF(String filePath, String name, String emailId, String phone, String operatingAirlines, Date departureDate, String departureCity, String arrivalCity) {//FIlePath is imp bcz it will determine wher ethe pdf file should generate.
        try {//generatePDF method will run after we save registration details into registration DB.
            Document document = new Document();//First we create a Document object.
            PdfWriter.getInstance(document, new FileOutputStream(filePath));//FileInputStream reads the file & FileOutputStream writes content into the file. Then we r supplying the filePath to the FileOutputStream(filePath) 
            document.open();//Then we are opening the document for writing contents.
            addMetaData(document);//Then we are creating a method and supplying the document to it, and we r calling the method.
            addTitleAndTable(document,name,emailId,phone,operatingAirlines, departureDate.toString(),departureCity,arrivalCity);//Another method is created and being called. Where we have supplied the document which already consist of the contents written in metaData method.
           
            document.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // iText allows to add metadata to the PDF which can be viewed in your Adobe
    // Reader
    // under File -> Properties
    private static void addMetaData(Document document) {
        document.addTitle("My first PDF");//When the method is called this title gets added.
        document.addSubject("Using iText");
        document.addKeywords("Java, PDF, iText");
        document.addAuthor("Lars Vogel");
        document.addCreator("Lars Vogel");
    }

    private static void addTitleAndTable(Document document, String name, String emailId, String phone, String operatingAirlines, String departureDate, String departureCity, String arrivalCity)
            throws DocumentException {
        Paragraph preface = new Paragraph();//We r preparing a paragraph.
        
        preface.add(new Paragraph("Flight Booking Details", catFont));//And in the paragraph we r writing the Heading for the para. And also we r using the catFont.

        preface.add(new Paragraph(//Then we r adding a new paragraph.
                "Report generated by: " + "Flight Reservation Company " + new Date(), //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$
                smallBold));//Here the new Date() will generate the current date whenever the pdf is being generated.
       
        document.add(preface);  
        document.add( Chunk.NEWLINE );//Here we r moving to new line.
        document.add( Chunk.NEWLINE );//Here we r moving to new line.
        
        PdfPTable table = new PdfPTable(2);//Here v r creating a new table in file.
        table.setWidthPercentage(100);//Means complete page to be covered. And set the width to 100.
        // t.setBorderColor(BaseColor.GRAY);
        // t.setPadding(4);
        // t.setSpacing(4);
        // t.setBorderWidth(1);

        PdfPCell c1 = new PdfPCell(new Phrase("Passenger Detail"));//We r forming a new cell in the table.
        c1.setHorizontalAlignment(Element.ALIGN_CENTER);//Aligning the text in the cell.
        c1.setColspan(2);//Meaning we r merging the 2 columns of the table for the cell.
        table.addCell(c1);//And we r feeding the changes to the table.

        table.addCell("Passenger name");//We are adding the cell data one by one.
        table.addCell(name);
        table.addCell("Email Id");
        table.addCell(emailId);
        table.addCell("Phone Number");
        table.addCell(phone);
        //One table is formed.
        document.add(table);//We r adding another table below it.
        
        PdfPTable table1 = new PdfPTable(2);//Another table is created and the reference variable name is table1.
        table1.setWidthPercentage(100);//Again we r setting the coverage as 100.
        // t.setBorderColor(BaseColor.GRAY);
        // t.setPadding(4);
        // t.setSpacing(4);
        // t.setBorderWidth(1);

        PdfPCell c2 = new PdfPCell(new Phrase("Flight Detail"));//Again we r providing heading.
        c2.setHorizontalAlignment(Element.ALIGN_CENTER);//Aligning center.
        c2.setColspan(2);
        table1.addCell(c2);

        table1.addCell("Operating Airlines");//Again we r filling the table data one by one.
        table1.addCell(operatingAirlines);
        table1.addCell("Departure Date");
        table1.addCell(departureDate);
        table1.addCell("Departure City");
        table1.addCell(departureCity);
        
        table1.addCell("Arrival City");
        table1.addCell(arrivalCity);
        
        document.add(table1);//Then we r creating the table into document. 
       
        document.close();//And we r closing the document to save all the changes.
    }  
}
